version: 2.1

jobs:
  build:
    macos:
      xcode: "15.4.0"
    environment:
      OUTPUT_DIR: /Users/distiller/Library/Developer/Xcode/DerivedData
      CONFIGURATION_BUILD_DIR: /Users/distiller/Library/Developer/Xcode/DerivedData/Tirajosaure-fjxtttdvoeihhkeornjdvafkbldn/Build/Products/Debug-iphonesimulator
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: List available simulators
          command: xcrun simctl list
      - run:
          name: Create DerivedData Directory
          command: mkdir -p /Users/distiller/Library/Developer/Xcode/DerivedData
      - run:
          name: Fix Permissions
          command: sudo chmod -R 777 /Users/distiller/Library/Developer/Xcode/DerivedData
      - run:
          name: Build and Test
          command: |
            set -o pipefail &&
            xcodebuild -workspace Tirajosaure.xcworkspace \
              -scheme Tirajosaure \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,id=2D935222-DF5D-4586-A392-CC13B82324BA' \
              build test | xcpretty

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
